version: "3.9"

services:
  db:
    image: postgres:16
    container_name: orders_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: wb_orders
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: orders_app
    depends_on:
    - db
    ports:
    - "8080:8080"
    env_file:
    - .env

volumes:
  db_data:
